#baseURL: "https://PC-Admin.github.io/perthserverplus.com"
baseURL: "https://PC-Admin.gitlab.io/perthserverplus.com/"
theme: "up-business-theme"
languageCode: "en-au"

title: "PerthServerPlus+"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "PerthServerPlus+"
  description: "We specialize in providing services to designing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "https://www.linkedin.com/company/perthserverplus/"
    facebook: "https://www.facebook.com/perthserverplus/"
    github: "https://github.com/PC-Admin/"
    gitlab: "https://gitlab.com/PC-Admin/"

  location:
    - "Perth, Western Australia"

  contact:
    - "michael@perthserverplus.com"
    - "+61 490 435 377"

  copyright: "© 2023 PerthServerPlus+ All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Services"
      url: "/#"
      weight: 2

    - name: "Pricing"
      url: "/#"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 4
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Services"
      url: "/#"
      weight: 2

    - name: "Pricing"
      url: "/#"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 4

taxonomies:
  series: "series"
  tags: "tags"
